In [15]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv

## Load Config

In [53]:
load_dotenv()

True

In [5]:
TMDB_API_KEY = os.getenv("TMDB_API_KEY")
TMDB_BASE_URL = os.getenv("TMDB_BASE_URL")

## APIs

### Popular Movies

In [8]:
def get_popular_movies(page=1, language="en-UK"):
    url = f"{TMDB_BASE_URL}/movie/popular"

    params = {
        "api_key": TMDB_API_KEY,
        "page": page,
        "language": language
    }

    response = requests.get(url, params=params)
    return response.json()

### Genre Mapping

In [10]:
def get_genre_mapping(language="en-UK"):
    url = f"{TMDB_BASE_URL}/genre/movie/list"

    params = {
        "api_key": TMDB_API_KEY,
        "language": language
    }

    response = requests.get(url, params=params)
    return response.json()

### Movie Details

In [12]:
def get_movie_details(movie_id, language="en-UK"):
    url = f"{TMDB_BASE_URL}/movie/{movie_id}"

    params = {
        "api_key": TMDB_API_KEY,
        "language": language
    }

    response = requests.get(url, params=params)
    return response.json()

### Cast

In [27]:
def get_movie_cast(movie_id, language="en-UK"):
    url = f"{TMDB_BASE_URL}/movie/{movie_id}/credits"

    params = {
        "api_key": TMDB_API_KEY,
        "language": language
    }

    response = requests.get(url, params=params)
    return response.json()

## Into DataFrame

In [17]:
popular_list = get_popular_movies()
df_popular_movies = pd.DataFrame(popular_list['results'])
df_popular_movies

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg,"[878, 28, 12]",969681,Spider-Man: Brand New Day,en,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,704.4472,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,2026-07-29,False,False,7.860,2799
1,False,/1CIaRYKf3zg2Xyce1CSfCMg2Vfw.jpg,"[27, 878, 12]",1423191,Resident Evil,en,Resident Evil,Medical courier Bryan unwittingly finds himsel...,525.4108,/i7UyjfPio0VFHB9rBUZSFyhOoM8.jpg,2026-09-16,False,False,7.362,235
2,False,/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg,"[878, 9648, 53]",1101383,The End of Oak Street,en,The End of Oak Street,After a mysterious cosmic event rips Oak Stree...,566.3338,/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg,2026-08-12,False,False,7.000,1339
3,False,/7GOW6jod9lLurW5utokAatxg7ql.jpg,"[35, 12, 10751]",1204680,Coyote vs. Acme,en,Coyote vs. Acme,After Acme products fail him one too many time...,472.0999,/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg,2026-08-20,False,False,7.560,468
4,False,/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg,"[12, 28, 14]",1368337,The Odyssey,en,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",387.2478,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,2026-07-15,False,False,8.015,3826
5,False,/hpBGCnzOvdtQoMyE48gvwp2y5yx.jpg,"[28, 27, 878]",1375646,Colony,ko,군체,Professor Se-jeong is thrust into a bloody nig...,357.8035,/tN799oUR0f1gUKDYdMNrDaY7I51.jpg,2026-05-21,False,False,8.092,838
6,False,/iRIhPqqoUHiFBxn8oYf3gCQnaKk.jpg,"[28, 53]",1294189,The Mongoose,en,The Mongoose,A falsely accused war hero with nothing to los...,248.1471,/eSS5mvSG84UUuvtbHel5Yu3Wik4.jpg,2026-10-29,False,False,0.000,0
7,False,/e2QAGrEmbpmZpMymDRkDisJkvg9.jpg,"[28, 53]",1288445,Mutiny,en,Mutiny,After witnessing his billionaire boss' murder ...,211.6718,/pu2VxGlpGwffOx292w18b1tv96j.jpg,2026-08-19,False,False,6.432,425
8,False,/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg,"[10751, 14, 35, 12]",1108427,Moana,en,Moana,"Teenage Moana answers the Ocean's call and, fo...",213.0753,/gaet1xQ2nxrG0V1Ep9T20ZMNEIC.jpg,2026-07-08,False,False,7.402,724
9,False,/yjK3ardrgdS8suZG8KMU82Q7U38.jpg,[10749],1285366,Shape of My Heart,ja,愛のぬくもり,"A romance about a man and a woman who, due to ...",217.7424,/3r0O6BW9USoZ9mteCVyNKMQriRL.jpg,2024-07-06,False,False,5.688,8
10,False,/sbkkAtymJaH5UzExiK974uPzCY4.jpg,"[28, 53]",1482547,Zip Wire,en,Zip Wire,When her ground-breaking pharmaceutical discov...,223.0139,/cO7J0XSVKPlAjUCMWC7DVBn1Py2.jpg,2026-08-31,False,False,7.600,12
11,False,/i65y7cMae36K0giN0GRaMjAHUru.jpg,"[10749, 53]",1440098,Drawn Together,es,Enfrentados: Marfil,"Marfil, daughter of a powerful Spanish busines...",164.1372,/6rpvddXbaQPOi0fB2HKWbZ3uUSg.jpg,2026-09-09,False,False,6.637,106
12,False,/qjTqY5coNiz6sVtPng40IzltsoN.jpg,"[16, 10751, 35, 12]",1084244,Toy Story 5,en,Toy Story 5,When Bonnie receives a Lilypad tablet as a gif...,159.0305,/sfQtVlIHljToOwYjhe21KPGzZWK.jpg,2026-06-17,False,False,8.361,2227
13,False,/jzBWExXacS33rMQ2zLBrqIVweyG.jpg,"[53, 28]",1386315,The Runner,en,The Runner,"Maia Marten, a brilliant London lawyer, has he...",149.7179,/uxCaBoYXsDC4A0SqTm3SISj0OwK.jpg,2026-09-03,False,False,6.767,536
14,False,/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg,"[27, 53]",1339713,Obsession,en,Obsession,"After breaking the mysterious ""One Wish Willow...",147.6875,/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg,2026-05-13,False,False,8.192,5642
15,False,/nfNaAiiILjYRc2CKkId1ZfPTtlh.jpg,"[18, 10749, 35]",1408162,Vishwanath & Sons,ta,விஸ்வநாத் & சன்ஸ்,A celebrated Olympian shooter travels to Ameri...,120.5753,/mLsvCffzpxxDwC7yVLJSLLjgzoq.jpg,2026-08-14,False,False,7.241,26
16,False,/dNKFETDDujxm2PUN873Jwiw5VML.jpg,"[27, 14, 9648]",1232569,Pinocchio: Unstrung,en,Pinocchio: Unstrung,Influenced by a sinister Cricket and created b...,142.8626,/eUJXk3bTvLBi5Zcb0BCedZU7lVL.jpg,2026-07-22,False,False,6.600,105
17,False,/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg,"[12, 16, 35, 10751, 14]",1315772,Minions & Monsters,en,Minions & Monsters,"This is the rambunctious, ridiculous and total...",132.5792,/4LwvU9SZc8QQzW1X1FAPhNbXnEU.jpg,2026-06-24,False,False,7.556,1151
18,False,/vP7YFt9pP8NPCg4PMBAHO5ILdrQ.jpg,"[28, 53]",44980,Zero Woman 2,ja,Zero WOMAN ＩＩ 警視庁０課の女,"When a valuable suitcase is stolen, the mob, p...",131.6220,/sQHeDjwmBQba8E51Mkp5dvgkzeZ.jpg,1995-09-05,False,False,5.000,8
19,False,/z7lZgL5tzefTfhyRtouThFhsuUS.jpg,"[28, 878, 53]",1323244,Rage of Stars,en,Rage of Stars,A story about a woman from the International S...,130.7482,/oLld47ZT1I3iecM3OWhIphohQUJ.jpg,2026-08-06,False,False,6.616,159

## Mapping the genre

In [20]:
genre_list = get_genre_mapping()
genre_dict = { g['id']: g['name'] for g in genre_list['genres'] }
genre_dict

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [23]:
df_popular_movies['genre_names'] = df_popular_movies.genre_ids.apply(
    lambda list: [genre_dict.get(i) for i in list]
)

df_popular_movies

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count,genre_names
0,False,/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg,"[878, 28, 12]",969681,Spider-Man: Brand New Day,en,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,704.4472,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,2026-07-29,False,False,7.860,2799,"[Science Fiction, Action, Adventure]"
1,False,/1CIaRYKf3zg2Xyce1CSfCMg2Vfw.jpg,"[27, 878, 12]",1423191,Resident Evil,en,Resident Evil,Medical courier Bryan unwittingly finds himsel...,525.4108,/i7UyjfPio0VFHB9rBUZSFyhOoM8.jpg,2026-09-16,False,False,7.362,235,"[Horror, Science Fiction, Adventure]"
2,False,/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg,"[878, 9648, 53]",1101383,The End of Oak Street,en,The End of Oak Street,After a mysterious cosmic event rips Oak Stree...,566.3338,/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg,2026-08-12,False,False,7.000,1339,"[Science Fiction, Mystery, Thriller]"
3,False,/7GOW6jod9lLurW5utokAatxg7ql.jpg,"[35, 12, 10751]",1204680,Coyote vs. Acme,en,Coyote vs. Acme,After Acme products fail him one too many time...,472.0999,/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg,2026-08-20,False,False,7.560,468,"[Comedy, Adventure, Family]"
4,False,/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg,"[12, 28, 14]",1368337,The Odyssey,en,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",387.2478,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,2026-07-15,False,False,8.015,3826,"[Adventure, Action, Fantasy]"
5,False,/hpBGCnzOvdtQoMyE48gvwp2y5yx.jpg,"[28, 27, 878]",1375646,Colony,ko,군체,Professor Se-jeong is thrust into a bloody nig...,357.8035,/tN799oUR0f1gUKDYdMNrDaY7I51.jpg,2026-05-21,False,False,8.092,838,"[Action, Horror, Science Fiction]"
6,False,/iRIhPqqoUHiFBxn8oYf3gCQnaKk.jpg,"[28, 53]",1294189,The Mongoose,en,The Mongoose,A falsely accused war hero with nothing to los...,248.1471,/eSS5mvSG84UUuvtbHel5Yu3Wik4.jpg,2026-10-29,False,False,0.000,0,"[Action, Thriller]"
7,False,/e2QAGrEmbpmZpMymDRkDisJkvg9.jpg,"[28, 53]",1288445,Mutiny,en,Mutiny,After witnessing his billionaire boss' murder ...,211.6718,/pu2VxGlpGwffOx292w18b1tv96j.jpg,2026-08-19,False,False,6.432,425,"[Action, Thriller]"
8,False,/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg,"[10751, 14, 35, 12]",1108427,Moana,en,Moana,"Teenage Moana answers the Ocean's call and, fo...",213.0753,/gaet1xQ2nxrG0V1Ep9T20ZMNEIC.jpg,2026-07-08,False,False,7.402,724,"[Family, Fantasy, Comedy, Adventure]"
9,False,/yjK3ardrgdS8suZG8KMU82Q7U38.jpg,[10749],1285366,Shape of My Heart,ja,愛のぬくもり,"A romance about a man and a woman who, due to ...",217.7424,/3r0O6BW9USoZ9mteCVyNKMQriRL.jpg,2024-07-06,False,False,5.688,8,[Romance]
10,False,/sbkkAtymJaH5UzExiK974uPzCY4.jpg,"[28, 53]",1482547,Zip Wire,en,Zip Wire,When her ground-breaking pharmaceutical discov...,223.0139,/cO7J0XSVKPlAjUCMWC7DVBn1Py2.jpg,2026-08-31,False,False,7.600,12,"[Action, Thriller]"
11,False,/i65y7cMae36K0giN0GRaMjAHUru.jpg,"[10749, 53]",1440098,Drawn Together,es,Enfrentados: Marfil,"Marfil, daughter of a powerful Spanish busines...",164.1372,/6rpvddXbaQPOi0fB2HKWbZ3uUSg.jpg,2026-09-09,False,False,6.637,106,"[Romance, Thriller]"
12,False,/qjTqY5coNiz6sVtPng40IzltsoN.jpg,"[16, 10751, 35, 12]",1084244,Toy Story 5,en,Toy Story 5,When Bonnie receives a Lilypad tablet as a gif...,159.0305,/sfQtVlIHljToOwYjhe21KPGzZWK.jpg,2026-06-17,False,False,8.361,2227,"[Animation, Family, Comedy, Adventure]"
13,False,/jzBWExXacS33rMQ2zLBrqIVweyG.jpg,"[53, 28]",1386315,The Runner,en,The Runner,"Maia Marten, a brilliant London lawyer, has he...",149.7179,/uxCaBoYXsDC4A0SqTm3SISj0OwK.jpg,2026-09-03,False,False,6.767,536,"[Thriller, Action]"
14,False,/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg,"[27, 53]",1339713,Obsession,en,Obsession,"After breaking the mysterious ""One Wish Willow...",147.6875,/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg,2026-05-13,False,False,8.192,5642,"[Horror, Thriller]"
15,False,/nfNaAiiILjYRc2CKkId1ZfPTtlh.jpg,"[18, 10749, 35]",1408162,Vishwanath & Sons,ta,விஸ்வநாத் & சன்ஸ்,A celebrated Olympian shooter travels to Ameri...,120.5753,/mLsvCffzpxxDwC7yVLJSLLjgzoq.jpg,2026-08-14,False,False,7.241,26,"[Drama, Romance, Comedy]"
16,False,/dNKFETDDujxm2PUN873Jwiw5VML.jpg,"[27, 14, 9648]",1232569,Pinocchio: Unstrung,en,Pinocchio: Unstrung,Influenced by a sinister Cricket and created b...,142.8626,/eUJXk3bTvLBi5Zcb0BCedZU7lVL.jpg,2026-07-22,False,False,6.600,105,"[Horror, Fantasy, Mystery]"
17,False,/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg,"[12, 16, 35, 10751, 14]",1315772,Minions & Monsters,en,Minions & Monsters,"This is the rambunctious, ridiculous and total...",132.5792,/4LwvU9SZc8QQzW1X1FAPhNbXnEU.jpg,2026-06-24,False,False,7.556,1151,"[Adventure, Animation, Comedy, Family, Fantasy]"
18,False,/vP7YFt9pP8NPCg4PMBAHO5ILdrQ.jpg,"[28, 53]",44980,Zero Woman 2,ja,Zero WOMAN ＩＩ 警視庁０課の女,"When a valuable suitcase is stolen, the mob, p...",131.6220,/sQHeDjwmBQba8E51Mkp5dvgkzeZ.jpg,1995-09-05,False,False,5.000,8,"[Action, Thriller]"
19,False,/z7lZgL5tzefTfhyRtouThFhsuUS.jpg,"[28, 878, 53]",1323244,Rage of Stars,en,Rage of Stars,A story about a woman from the International S...,130.7482,/oLld47ZT1I3iecM3OWhIphohQUJ.jpg,2026-08-06,False,False,6.616,159,"[Action, Science Fiction, Thriller]"

## Movie details in DataFrame

In [26]:
details_list = []

for id in df_popular_movies['id'].head(5):
    detail = get_movie_details(id)
    details_list.append(detail)

df_details = pd.DataFrame(details_list)
df_details

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,origin_country,original_language,...,revenue,runtime,softcore,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg,"{'id': 531241, 'name': 'Spider-Man (MCU) Colle...",225000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://spidermanbrandnewday.movie,969681,tt22084616,[US],en,...,2478502286,145,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,A brand new day starts now.,Spider-Man: Brand New Day,False,7.860,2798
1,False,/1CIaRYKf3zg2Xyce1CSfCMg2Vfw.jpg,None,75000000,"[{'id': 27, 'name': 'Horror'}, {'id': 878, 'na...",https://residentevil.movie,1423191,tt35538033,[US],en,...,108300000,95,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,A new era of evil.,Resident Evil,False,7.342,231
2,False,/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg,None,80000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.endofoakstreet.com,1101383,tt27165187,[US],en,...,120363694,100,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Where goes the neighborhood.,The End of Oak Street,False,7.000,1337
3,False,/7GOW6jod9lLurW5utokAatxg7ql.jpg,None,72000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 12, 'nam...",https://coyotevsacme.com,1204680,tt1756855,[US],en,...,79825108,103,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The movie ACME doesn't want you to see.,Coyote vs. Acme,False,7.600,468
4,False,/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg,None,250000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.universalpictures.com/movies/the-o...,1368337,tt33764258,"[GB, US]",en,...,1721314740,173,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Defy the gods.,The Odyssey,False,8.000,3824

## Add Cast into main df

In [42]:
cast_list = []

for id in df_popular_movies.id:
    cast = get_movie_cast(id)
    top_5 = cast['cast'][:5]
    cast_list.append({
        'cast': [{'name': i['name'], 'character': i['character']} for i in top_5]
    })

df_popular_movies['cast'] = cast_list

In [43]:
df_popular_movies

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count,genre_names,cast
0,False,/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg,"[878, 28, 12]",969681,Spider-Man: Brand New Day,en,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,704.4472,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,2026-07-29,False,False,7.860,2799,"[Science Fiction, Action, Adventure]","{'cast': [{'name': 'Tom Holland', 'character':..."
1,False,/1CIaRYKf3zg2Xyce1CSfCMg2Vfw.jpg,"[27, 878, 12]",1423191,Resident Evil,en,Resident Evil,Medical courier Bryan unwittingly finds himsel...,525.4108,/i7UyjfPio0VFHB9rBUZSFyhOoM8.jpg,2026-09-16,False,False,7.362,235,"[Horror, Science Fiction, Adventure]","{'cast': [{'name': 'Austin Abrams', 'character..."
2,False,/b9q9VmbXDvJmTziRqkwdEmFdwhr.jpg,"[878, 9648, 53]",1101383,The End of Oak Street,en,The End of Oak Street,After a mysterious cosmic event rips Oak Stree...,566.3338,/fYXqpgPmHMphSF2W30GbTeJVIa5.jpg,2026-08-12,False,False,7.000,1339,"[Science Fiction, Mystery, Thriller]","{'cast': [{'name': 'Anne Hathaway', 'character..."
3,False,/7GOW6jod9lLurW5utokAatxg7ql.jpg,"[35, 12, 10751]",1204680,Coyote vs. Acme,en,Coyote vs. Acme,After Acme products fail him one too many time...,472.0999,/kYDCl2y0VPvhT5eYWbMRInPoB03.jpg,2026-08-20,False,False,7.560,468,"[Comedy, Adventure, Family]","{'cast': [{'name': 'Will Forte', 'character': ..."
4,False,/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg,"[12, 28, 14]",1368337,The Odyssey,en,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",387.2478,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,2026-07-15,False,False,8.015,3826,"[Adventure, Action, Fantasy]","{'cast': [{'name': 'Matt Damon', 'character': ..."
5,False,/hpBGCnzOvdtQoMyE48gvwp2y5yx.jpg,"[28, 27, 878]",1375646,Colony,ko,군체,Professor Se-jeong is thrust into a bloody nig...,357.8035,/tN799oUR0f1gUKDYdMNrDaY7I51.jpg,2026-05-21,False,False,8.092,838,"[Action, Horror, Science Fiction]","{'cast': [{'name': 'Gianna Jun', 'character': ..."
6,False,/iRIhPqqoUHiFBxn8oYf3gCQnaKk.jpg,"[28, 53]",1294189,The Mongoose,en,The Mongoose,A falsely accused war hero with nothing to los...,248.1471,/eSS5mvSG84UUuvtbHel5Yu3Wik4.jpg,2026-10-29,False,False,0.000,0,"[Action, Thriller]","{'cast': [{'name': 'Liam Neeson', 'character':..."
7,False,/e2QAGrEmbpmZpMymDRkDisJkvg9.jpg,"[28, 53]",1288445,Mutiny,en,Mutiny,After witnessing his billionaire boss' murder ...,211.6718,/pu2VxGlpGwffOx292w18b1tv96j.jpg,2026-08-19,False,False,6.432,425,"[Action, Thriller]","{'cast': [{'name': 'Jason Statham', 'character..."
8,False,/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg,"[10751, 14, 35, 12]",1108427,Moana,en,Moana,"Teenage Moana answers the Ocean's call and, fo...",213.0753,/gaet1xQ2nxrG0V1Ep9T20ZMNEIC.jpg,2026-07-08,False,False,7.402,724,"[Family, Fantasy, Comedy, Adventure]","{'cast': [{'name': 'Catherine Lagaʻaia', 'char..."
9,False,/yjK3ardrgdS8suZG8KMU82Q7U38.jpg,[10749],1285366,Shape of My Heart,ja,愛のぬくもり,"A romance about a man and a woman who, due to ...",217.7424,/3r0O6BW9USoZ9mteCVyNKMQriRL.jpg,2024-07-06,False,False,5.688,8,[Romance],"{'cast': [{'name': 'Keisuke Koide', 'character..."
10,False,/sbkkAtymJaH5UzExiK974uPzCY4.jpg,"[28, 53]",1482547,Zip Wire,en,Zip Wire,When her ground-breaking pharmaceutical discov...,223.0139,/cO7J0XSVKPlAjUCMWC7DVBn1Py2.jpg,2026-08-31,False,False,7.600,12,"[Action, Thriller]","{'cast': [{'name': 'MyAnna Buring', 'character..."
11,False,/i65y7cMae36K0giN0GRaMjAHUru.jpg,"[10749, 53]",1440098,Drawn Together,es,Enfrentados: Marfil,"Marfil, daughter of a powerful Spanish busines...",164.1372,/6rpvddXbaQPOi0fB2HKWbZ3uUSg.jpg,2026-09-09,False,False,6.637,106,"[Romance, Thriller]","{'cast': [{'name': 'Ester Expósito', 'characte..."
12,False,/qjTqY5coNiz6sVtPng40IzltsoN.jpg,"[16, 10751, 35, 12]",1084244,Toy Story 5,en,Toy Story 5,When Bonnie receives a Lilypad tablet as a gif...,159.0305,/sfQtVlIHljToOwYjhe21KPGzZWK.jpg,2026-06-17,False,False,8.361,2227,"[Animation, Family, Comedy, Adventure]","{'cast': [{'name': 'Joan Cusack', 'character':..."
13,False,/jzBWExXacS33rMQ2zLBrqIVweyG.jpg,"[53, 28]",1386315,The Runner,en,The Runner,"Maia Marten, a brilliant London lawyer, has he...",149.7179,/uxCaBoYXsDC4A0SqTm3SISj0OwK.jpg,2026-09-03,False,False,6.767,536,"[Thriller, Action]","{'cast': [{'name': 'Gal Gadot', 'character': '..."
14,False,/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg,"[27, 53]",1339713,Obsession,en,Obsession,"After breaking the mysterious ""One Wish Willow...",147.6875,/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg,2026-05-13,False,False,8.192,5642,"[Horror, Thriller]","{'cast': [{'name': 'Michael Johnston', 'charac..."
15,False,/nfNaAiiILjYRc2CKkId1ZfPTtlh.jpg,"[18, 10749, 35]",1408162,Vishwanath & Sons,ta,விஸ்வநாத் & சன்ஸ்,A celebrated Olympian shooter travels to Ameri...,120.5753,/mLsvCffzpxxDwC7yVLJSLLjgzoq.jpg,2026-08-14,False,False,7.241,26,"[Drama, Romance, Comedy]","{'cast': [{'name': 'Suriya', 'character': 'San..."
16,False,/dNKFETDDujxm2PUN873Jwiw5VML.jpg,"[27, 14, 9648]",1232569,Pinocchio: Unstrung,en,Pinocchio: Unstrung,Influenced by a sinister Cricket and created b...,142.8626,/eUJXk3bTvLBi5Zcb0BCedZU7lVL.jpg,2026-07-22,False,False,6.600,105,"[Horror, Fantasy, Mystery]","{'cast': [{'name': 'Jude Evan Lloyd', 'charact..."
17,False,/kkcwhgSFd81QDlXo8ytrpHPQjhy.jpg,"[12, 16, 35, 10751, 14]",1315772,Minions & Monsters,en,Minions & Monsters,"This is the rambunctious, ridiculous and total...",132.5792,/4LwvU9SZc8QQzW1X1FAPhNbXnEU.jpg,2026-06-24,False,False,7.556,1151,"[Adventure, Animation, Comedy, Family, Fantasy]","{'cast': [{'name': 'Pierre Coffin', 'character..."
18,False,/vP7YFt9pP8NPCg4PMBAHO5ILdrQ.jpg,"[28, 53]",44980,Zero Woman 2,ja,Zero WOMAN ＩＩ 警視庁０課の女,"When a valuable suitcase is stolen, the mob, p...",131.6220,/sQHeDjwmBQba8E51Mkp5dvgkzeZ.jpg,1995-09-05,False,False,5.000,8,"[Action, Thriller]","{'cast': [{'name': 'Natsuki Ozawa', 'character..."
19,False,/z7lZgL5tzefTfhyRtouThFhsuUS.jpg,"[28, 878, 53]",1323244,Rage of Stars,en,Rage of Stars,A story about a woman from the International S...,130.7482,/oLld47ZT1I3iecM3OWhIphohQUJ.jpg,2026-08-06,False,False,6.616,159,"[Action, Science Fiction, Thriller]","{'cast': [{'name': 'Andrea Tivadar', 'characte..."